### ISSUE TITLE
page must be lower than or equal to 30

### ISSUE THREAD

**Issue by brackio** [diegohaz/menquery#26]
How do I remove the max validation of the page.  I am getting this error.
max:30
message:"page must be lower than or equal to 30"
name:"max"
param:"page"
valid:false

**Comment by diegohaz** [comment]
Try this:
```js
querymen.middleware({
  page: {
    max: 100
  }
})
```

**Comment by brackio** [comment]
thanks.  Is there a way to remove this restraint?  I am doing pagination, and my pages can reach 300 and above.

**Comment by diegohaz** [comment]
It's good practice to define a maximum value, but you can always set max to `Infinity`. :)

**Comment by ShivamuruganS** [comment]
@diegohaz  You saved my day man, thanks a ton, you don't believe i was searching solution for this issue for 2 hours this is the only article i found for my exact case.
