### ISSUE TITLE
question on querymen default schema

### ISSUE THREAD

**Issue by khelkun** [diegohaz/menquery#54]
In the README:
```
User requests /posts?q=term&fields=title,desc req.querymen will be:

When user requests /posts?q=term, querymen parses it to {keywords: /term/i}. It was designed to work with mongoose-keywords plugin, which adds a keywords field to schemas (check that out).
```
I did look at mongoose-keywords but I have to admit that I don't really understand how it works. Anyway  the querymen README says "_When user requests /posts?q=term, querymen parses it to {keywords: /term/i}_". My question would be what's 'i' in 'term/i'?

**Comment by diegohaz** [comment]
Hi, @khelkun 

That's a regular expression. `i` means `case insensitive`.

**Comment by khelkun** [comment]
oh yes javascript regex, I should have figured that out . Sorry my bad.
