### ISSUE TITLE
[Question, Help needed] Remove Limit

### ISSUE THREAD

**Issue by andrewgamez** [diegohaz/menquery#64]
Hello!
Is there any way to show more than 100 results? or remove the limit?
thx

**Comment by diegohaz** [comment]
Yes, try this:
```js
querymen.middleware({
  page: {
    max: 1000
  }
})
```

To remove the limit, set it to `Infinity`

**Comment by fsalaysay** [comment]
Hi @diegohaz where do I put that code? I'm using the default directory/file structure from your REST API generator.

**Comment by drochag** [comment]
@fsalaysay on each `index.js` for the generated api endpoint you'll find a `query()`, which is the `querymen` middleware

**Comment by fsalaysay** [comment]
Hi @DanMMX 

Thanks for the help but I tried

```javascript
router.get('/',
  query(),
  index)
```
and
```javascript
router.get('/',
  query({}, { // using default schema
    page: {
      max: 1000
    }
  }),
  index)
```
but both still doesn't work and responds with just the default 30. I know you're supposed to pass options as the second argument, but yeah, still getting 30 items. Any help?

**Comment by drochag** [comment]
The example is the following @fsalaysay 

```
querymen.middleware({
  page: {
    max: 1000
  }
})
```

which you are not applying on yours. You can see [here](https://github.com/diegohaz/rest/blob/master/generators/api/templates/index.js#L37) the following:

```
import { middleware as query } from 'querymen'
```

that means `querymen.middleware` is renamed to `query`. So that means you need to do

```
query({
  page: {
    max: 1000
  }
})
```

instead of what you're doing (`query()` and `query({}, { page: { max: 1000 }})`)

**Comment by DiegoPerea** [comment]
Can I remove the limit from the Schema?
I have this:
`var schema = new querymen.Schema({
  sort: '-creationDate',
  search: {
    type: RegExp,
    paths: ['name', 'description']
  }
})`

AND

`querymen.middleware(schema)`

But if I add `page: {max: 1000}`, it has an error

**Comment by drochag** [comment]
What's the error @DiegoPerea ?
Have you tried `Infinity` as `max` limit?

**Comment by ImamCandra** [comment]
> The example is the following @fsalaysay
> 
> ```
> querymen.middleware({
>   page: {
>     max: 1000
>   }
> })
> ```
> which you are not applying on yours. You can see [here](https://github.com/diegohaz/rest/blob/master/generators/api/templates/index.js#L37) the following:
> 
> ```
> import { middleware as query } from 'querymen'
> ```
> that means `querymen.middleware` is renamed to `query`. So that means you need to do
> 
> ```
> query({
>   page: {
>     max: 1000
>   }
> })
> ```
> instead of what you're doing (`query()` and `query({}, { page: { max: 1000 }})`)

Hi @DanMMX 
It's still not work for me. please help

**Comment by drochag** [comment]
Can you share your code or something we can work from @ImamCandra ?

**Comment by Varimatrass** [comment]
This is not
query({ page: { max: 1000 } })
but
query({ limit: { max: 1000 } })

have a good day :)
